### ISSUE TITLE
PSK Reporter

### ISSUE THREAD

**Issue by MaverickNH** [wITTus/ft8rx.github.io#2]
Suggestion - Might there be a way to create an option to upload spots to PSK Reporter from the app?

Bret/N4SRN

**Comment by wITTus** [comment]
Yes, definitely. In fact, this is part of the reason why I'm asking for a call sign on the configuration page (which is quite useless right now).

The only thing that prevents me from implementing it is the still missing correct dB calculation for the received signals (I didn't want to cause confusion among hams with wrong values). Now, I guess I could send an incomplete report (without dB value) to PSK Reporter but it doesn't feel good enough.

Additional note: There might be GDPR issues with this. After all, implementing this feature would mean that FT8RX suddenly collects data from a mobile phone and sends it to some third party website. An update to the privacy policy of FT8RX might be necessary, because of the current wording: "For a better experience, while using our Service, I may require you to provide us with certain personally identifiable information. The information that I request will be retained on your device and is not collected by me in any way."

I'll keep this issue open. It would be a great addition to the app.

**Comment by wITTus** [comment]
Done :)
